### ISSUE TITLE
Issue in Kavita.txt

### ISSUE THREAD

**Issue by omkarl08** [omkarl08/test#6]
Please review line 2 there's mistakenly hello written at place of 'Bolo'

**Comment by omkarl08** [comment]
#6 Thank You for your review definitely I will update that.

**Comment by opOMK** [comment]
jthjthjhjjjjjjjjj

**Comment by omkarl08** [comment]
hhhhh

**Comment by omkarl08** [comment]
hhhh

**Comment by opOMK** [comment]
hhhjkl
